name: Push components to Espressif Component Service

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "micropython-helper"
          namespace: "mr9you"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}